const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const D={};
const W={need:26,production:22,market:16,upside:14,health:10,flex:12};
const FLEX=new Set(['RB','WR','TE']);

async function j(path,fallback=null){try{const r=await fetch(path+'?v='+Date.now());if(!r.ok)throw 0;return await r.json()}catch(e){return fallback}}
async function boot(){
 const [status,league,teams,myTeam,freeAgents,trending,matchups,transactions,draftPicks,news,schedule]=await Promise.all([
  j('data/status.json',{}),j('data/league.json',{}),j('data/teams.json',[]),j('data/my_team.json',{}),j('data/free_agents.json',[]),j('data/trending.json',{add:[],drop:[]}),j('data/matchups.json',[]),j('data/transactions.json',[]),j('data/draft_picks.json',[]),j('data/news.json',[]),j('data/schedule.json',[])
 ]);
 Object.assign(D,{status,league,teams,myTeam,freeAgents,trending,matchups,transactions,draftPicks,news,schedule});
 D.heat=heatMap(); D.draft=draftMap(); D.myOwned=new Set((myTeam.players||[]).map(p=>p.player_id));
 $('#weekPill').textContent='Week '+(status.current_week||'—');
 $('#faabPill').textContent='FAAB $'+remainingFaab();
 $('#syncText').textContent='Synced '+ago(status.refreshed_at_utc);
 const src=status.sources||{}; $('#sourcePill').innerHTML=`<span class="pulse-dot"></span> ${Object.values(src).filter(Boolean).length||1} SOURCES`;
 renderAll(); bindNav(); installDrawer();
}
function remainingFaab(){return Math.max(0,(D.league.settings?.waiver_budget||200)-(D.myTeam.settings?.waiver_budget_used||0))}
function ago(iso){if(!iso)return'unknown';const m=Math.max(0,Math.floor((Date.now()-new Date(iso))/60000));return m<2?'just now':m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'}
function heatMap(){const m={};(D.trending.add||[]).forEach((x,i)=>m[x.player_id]=(m[x.player_id]||0)+Math.min(100,45+(x.count||0)*.18+(120-i)*.35));(D.trending.drop||[]).forEach((x,i)=>m[x.player_id]=(m[x.player_id]||0)-Math.min(85,25+(x.count||0)*.12+(100-i)*.2));return m}
function draftMap(){const m={};(D.draftPicks||[]).forEach(x=>m[x.player_id]=x);return m}
function stats(p){return p.stats||null}
function ppg(p){const s=stats(p);return s&&s.games?+(s.fantasy_points_ppr/s.games).toFixed(1):0}
function touches(p){const s=stats(p);return s?Math.round((s.carries||0)+(s.targets||0)):0}
function volumeScore(p){const s=stats(p);if(!s)return 40;const g=Math.max(1,s.games||1),vol=((s.carries||0)+(s.targets||0))/g;return Math.min(100,Math.round(vol*5.2))}
function productionScore(p){const x=ppg(p);if(!x)return 42;return Math.min(100,Math.round(x*4.7))}
function health(p){const s=(p.injury_status||'').toLowerCase();if(!s)return 100;if(s.includes('question'))return 62;if(s.includes('doubt'))return 30;if(s.includes('out')||s.includes('ir'))return 10;return 50}
function upside(p){const y=Number(p.years_exp);const age=y<=1?88:y<=3?78:y<=6?62:47;const role=volumeScore(p);return Math.round(age*.58+role*.42)}
function scarcity(pos){return {RB:96,WR:90,TE:76,QB:49,K:20,DEF:24}[pos]||40}
function counts(t){const c={QB:0,RB:0,WR:0,TE:0,K:0,DEF:0};(t.players||[]).forEach(p=>{if(p.position in c)c[p.position]++});return c}
function need(t,pos){const c=counts(t),target={QB:1,RB:5,WR:5,TE:2,K:1,DEF:1}[pos]||1;return Math.max(15,Math.min(100,45+(target-(c[pos]||0))*23))}
function newsDelta(p){let d=0;(p.news||[]).slice(0,3).forEach(n=>{d+=n.impact==='positive'?10:n.impact==='negative'?-18:n.impact==='watch'?-7:0});return Math.max(-30,Math.min(20,d))}
function scheduleNote(p){const games=p.upcoming_games||[];if(!games.length)return'Upcoming schedule unavailable';const g=games[0],opp=g.home===p.team?g.away:g.home;return opp?`Next: ${p.team} vs ${opp}`:'Upcoming game loaded'}
function draftCapital(p){const d=D.draft[p.player_id];if(!d)return 35;return Math.max(25,100-(d.pick_no||100)*.8)}
function value(p,starter=false){let v=productionScore(p)*.29+volumeScore(p)*.19+upside(p)*.15+scarcity(p.position)*.12+health(p)*.09+Math.max(0,Math.min(100,D.heat[p.player_id]||0))*.08+draftCapital(p)*.08+newsDelta(p)*.25+(starter?9:0);if(p.position==='K'||p.position==='DEF')v*=.62;return Math.max(1,Math.min(99,Math.round(v)))}
function waiverScore(p){const n=need(D.myTeam,p.position),prod=productionScore(p),market=Math.max(0,Math.min(100,D.heat[p.player_id]||0)),up=upside(p),h=health(p),fx=FLEX.has(p.position)?92:48;const total=W.need+W.production+W.market+W.upside+W.health+W.flex;return Math.round((n*W.need+prod*W.production+market*W.market+up*W.upside+h*W.health+fx*W.flex)/total)}
function faab(s,p){const left=remainingFaab(),base=s>=90?.18:s>=84?.13:s>=78?.09:s>=70?.055:s>=62?.025:.01;let b=Math.max(1,Math.round(left*base));if(p.position==='QB'||p.position==='TE')b=Math.round(b*.82);return Math.max(1,b)}
function dropList(){return (D.myTeam.players||[]).filter(p=>!p.starter&&!['K','DEF'].includes(p.position)).map(p=>({...p,_v:value(p)})).sort((a,b)=>a._v-b._v)}
function topWaivers(n=20,pos='ALL'){return (D.freeAgents||[]).filter(p=>p.team&&(!p.status||String(p.status).toLowerCase()!=='inactive')&&(pos==='ALL'||p.position===pos)).map(p=>({...p,_w:waiverScore(p),_v:value(p)})).sort((a,b)=>b._w-a._w).slice(0,n)}
function posGrade(t,pos){const a=(t.players||[]).filter(p=>p.position===pos).map(p=>value(p,p.starter)).sort((a,b)=>b-a),n={QB:1,RB:4,WR:4,TE:2}[pos]||1;return Math.round(a.slice(0,n).reduce((x,y)=>x+y,0)/Math.max(1,a.slice(0,n).length))}
function teamGrade(t){return Math.round(['QB','RB','WR','TE'].reduce((a,p)=>a+posGrade(t,p),0)/4)}
function statline(p){const s=stats(p);if(!s)return'<span class="stat-chip">No 2026 game stats yet</span>';let x=[`${ppg(p)} PPR/G`];if(p.position==='RB')x.push(`${Math.round(s.carries||0)} car`,`${Math.round(s.targets||0)} tgt`);if(p.position==='WR'||p.position==='TE')x.push(`${Math.round(s.targets||0)} tgt`,`${Math.round(s.receptions||0)} rec`);if(p.position==='QB')x.push(`${Math.round(s.passing_yards||0)} pass yd`,`${Math.round(s.passing_tds||0)} TD`);return x.map(v=>`<span class="stat-chip">${v}</span>`).join('')}
function player(p){return `<div class="player"><span class="pos">${p.position||'?'}</span><div><strong>${p.name}</strong><div class="sub">${p.team||'FA'}${p.injury_status?' · '+p.injury_status:''}</div></div></div>`}
function bar(n){return `<div class="bar"><i style="width:${Math.max(3,Math.min(100,n))}%"></i></div>`}
function decision(s){return s>=84?'claim':s>=70?'watch':'avoid'}
function addReasons(p,drop){let r=[];if(ppg(p)>0)r.push(`${ppg(p)} PPR points per game through recorded 2026 games`);if(volumeScore(p)>60)r.push(`strong opportunity volume (${touches(p)} carries + targets)`);if((D.heat[p.player_id]||0)>35)r.push('being added aggressively across Sleeper');if(FLEX.has(p.position))r.push('can directly compete for one of your two FLEX spots');if((p.news||[]).some(n=>n.impact==='positive'))r.push('recent news improves role/upside');if(drop)r.push(`${Math.max(0,value(p)-drop._v)} model-value points above ${drop.name}`);if(!r.length)r.push('depth/upside profile is better than replacement-level options');return r.slice(0,4)}
function renderAll(){command();waivers();trades();news();league();roster();model()}
function command(){const tw=topWaivers(5),dl=dropList(),grades=Object.fromEntries(['QB','RB','WR','TE'].map(p=>[p,posGrade(D.myTeam,p)])),weak=Object.entries(grades).sort((a,b)=>a[1]-b[1])[0];const urgent=(D.myTeam.players||[]).filter(p=>p.injury_status||((p.news||[]).some(n=>['negative','watch'].includes(n.impact)));$('#view-command').innerHTML=`
 ${urgent.length?`<div class="alert-strip"><div>⚠</div><div><strong>${urgent.length} roster alert${urgent.length>1?'s':''}</strong><div class="sub">${urgent.slice(0,3).map(p=>p.name+(p.injury_status?' ('+p.injury_status+')':'')).join(' · ')}</div></div></div>`:''}
 <div class="hero"><div><div class="section-kicker">Your live GM brief</div><h2>${weak[0]} is currently the roster room with the least leverage.</h2><p>Every recommendation below is generated against the actual players owned in this league, your $${remainingFaab()} remaining FAAB, current roster construction, live Sleeper market movement, recorded 2026 production and league-relevant news.</p><div class="source-row">${Object.entries(D.status.sources||{}).map(([k,v])=>`<span class="source-chip ${v?'on':''}">${v?'✓':'○'} ${k.replace('_',' ')}</span>`).join('')}</div></div><div><div class="label">Team grade</div><div class="metric">${teamGrade(D.myTeam)}</div>${bar(teamGrade(D.myTeam))}<div class="sub">Weakest room: ${weak[0]} ${weak[1]}/100</div></div></div>
 <div class="grid cols-4" style="margin-top:16px"><div class="card"><div class="label">Waiver priority</div><div class="metric good">#${D.myTeam.settings?.waiver_position||'—'}</div><div class="sub">Preserve it for meaningful lineup gain</div></div><div class="card"><div class="label">Best available</div><div class="metric" style="font-size:18px">${tw[0]?.name||'—'}</div><div class="sub">Score ${tw[0]?tw[0]._w:'—'} · bid $${tw[0]?faab(tw[0]._w,tw[0]):0}</div></div><div class="card"><div class="label">First cut</div><div class="metric" style="font-size:18px">${dl[0]?.name||'—'}</div><div class="sub">Bench value ${dl[0]?dl[0]._v:'—'}</div></div><div class="card"><div class="label">Live news</div><div class="metric">${D.status.counts?.news||0}</div><div class="sub">league-relevant feed items loaded</div></div></div>
 <div class="section-title"><div><h2>Manager action queue</h2><p>The highest-value decisions to investigate first.</p></div></div><div class="action-stack">${tw.slice(0,4).map((p,i)=>actionCard(p,dl[0],i)).join('')}</div>`}
function actionCard(p,drop,i){const gain=drop?value(p)-drop._v:value(p);return `<div class="card action-card"><div class="action-head"><div><div class="label">Priority ${i+1}</div><div class="action-title">Add ${p.name}${drop?` · consider dropping ${drop.name}`:''}</div></div><span class="decision ${decision(p._w)}">${decision(p._w).toUpperCase()}</span></div><div class="mini-grid"><div class="mini"><b>${p._w}</b><span>claim score</span></div><div class="mini"><b>$${faab(p._w,p)}</b><span>suggested bid</span></div><div class="mini"><b class="${gain>=0?'good':'bad'}">${gain>=0?'+':''}${gain}</b><span>value delta</span></div></div><div class="statline">${statline(p)}</div><div class="reason-list">${addReasons(p,drop).map(x=>`<div class="reason-item">${x}</div>`).join('')}</div><div class="player-actions"><button class="tiny-btn" onclick="openPlayer('${p.player_id}','fa')">Full player case</button></div></div>`}
function waivers(){const dl=dropList();$('#view-waivers').innerHTML=`<div class="section-title"><div><div class="section-kicker">Real league availability</div><h2>Waiver Assassin</h2><p>Searches only players not rostered by any of the 10 teams.</p></div><div class="controls"><input id="ws" class="control search" placeholder="Search player"><select id="wp" class="control"><option>ALL</option><option>RB</option><option>WR</option><option>TE</option><option>QB</option><option>K</option></select></div></div><div id="wtable"></div><div class="section-title"><div><h2>Your drop ladder</h2><p>Lowest hold value first, with context rather than a blind ranking.</p></div></div><div class="grid cols-3">${dl.map((p,i)=>`<div class="card"><div class="label">Cut candidate #${i+1}</div>${player(p)}<div class="statline">${statline(p)}</div><div class="metric">${p._v}</div>${bar(p._v)}<p class="reason">${dropReason(p)}</p><button class="tiny-btn" onclick="openPlayer('${p.player_id}','mine')">Why hold/drop?</button></div>`).join('')}</div>`;const update=()=>{const q=$('#ws').value.toLowerCase(),pos=$('#wp').value;const list=(D.freeAgents||[]).filter(p=>p.team&&(pos==='ALL'||p.position===pos)&&p.name.toLowerCase().includes(q)).map(p=>({...p,_w:waiverScore(p)})).sort((a,b)=>b._w-a._w).slice(0,100);$('#wtable').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Player</th><th>2026</th><th>Claim</th><th>Market</th><th>FAAB</th><th>Why</th></tr></thead><tbody>${list.map((p,i)=>`<tr><td><span class="rank-badge">${i+1}</span></td><td>${player(p)}</td><td>${ppg(p)?ppg(p)+' PPG':'—'}<div class="sub">vol ${volumeScore(p)}</div></td><td><strong class="score">${p._w}</strong>${bar(p._w)}</td><td>${Math.round(D.heat[p.player_id]||0)}</td><td><strong>$${faab(p._w,p)}</strong></td><td><button class="tiny-btn" onclick="openPlayer('${p.player_id}','fa')">Explain</button></td></tr>`).join('')}</tbody></table></div>`};$('#ws').oninput=update;$('#wp').onchange=update;update()}
function dropReason(p){let r=[];if(ppg(p)&&ppg(p)<10)r.push(`only ${ppg(p)} PPR/G so far`);if(volumeScore(p)<45)r.push('limited recorded opportunity');if((D.heat[p.player_id]||0)<0)r.push('negative Sleeper market movement');if(p.injury_status)r.push(`${p.injury_status} injury status`);return r.length?r.join('; ')+'.':'Bench player still carries enough upside that I would only drop him for a clear upgrade.'}
function tradeIdeas(){let out=[];const mine=(D.myTeam.players||[]).filter(p=>!['K','DEF'].includes(p.position));for(const opp of D.teams.filter(t=>t.roster_id!==D.myTeam.roster_id)){const oppNeeds=Object.fromEntries(['QB','RB','WR','TE'].map(p=>[p,100-posGrade(opp,p)]));for(const target of opp.players.filter(p=>!['K','DEF'].includes(p.position))){const tv=value(target,target.starter);const myNeed=100-posGrade(D.myTeam,target.position);for(const give of mine.filter(p=>p.player_id!==target.player_id)){const gv=value(give,give.starter),fair=100-Math.min(100,Math.abs(tv-gv)*3),otherNeed=oppNeeds[give.position]||20,starterTax=target.starter?8:0,fit=Math.round(fair*.48+myNeed*.24+otherNeed*.2+(100-starterTax)*.08);if(fit>=55&&myNeed>15)out.push({opp,target,give,tv,gv,fit,myNeed,otherNeed})}}}return out.sort((a,b)=>b.fit-a.fit).slice(0,20)}
function trades(){const x=tradeIdeas();$('#view-trades').innerHTML=`<div class="hero"><div><div class="section-kicker">League-specific negotiation engine</div><h2>Trade for roster impact, not name value.</h2><p>Trade Lab looks for actual opponent weaknesses, your positional needs, player production, opportunity, health and a realistic value gap. The highest score means the conversation makes structural sense for both sides — not that the offer is guaranteed to be accepted.</p></div><div><div class="label">Best conversation</div><div class="metric">${x[0]?.fit||'—'}</div><div class="sub">fit / 100</div></div></div><div class="section-title"><div><h2>Best trade conversations now</h2><p>Use these as starting points and negotiate around them.</p></div></div><div class="grid cols-2">${x.map((a,i)=>`<div class="card"><div class="action-head"><div><div class="label">#${i+1} · ${a.opp.display_name}</div><div class="action-title">Target ${a.target.name}</div></div><span class="tag ${a.fit>=72?'good':'warn'}">FIT ${a.fit}</span></div><div class="vs-row"><div class="vs-box"><div class="sub">YOU SEND</div>${player(a.give)}<div class="statline">${statline(a.give)}</div><b>Value ${a.gv}</b></div><div class="vs-arrow">⇄</div><div class="vs-box"><div class="sub">YOU GET</div>${player(a.target)}<div class="statline">${statline(a.target)}</div><b>Value ${a.tv}</b></div></div><div class="reason-list"><div class="reason-item">Your need at ${a.target.position}: ${a.myNeed}/100</div><div class="reason-item">${a.opp.display_name}'s need at ${a.give.position}: ${a.otherNeed}/100</div><div class="reason-item">Modeled value gap: ${Math.abs(a.tv-a.gv)} points</div></div></div>`).join('')||'<div class="card empty">No clean one-for-one trade structures score highly enough right now.</div>'}</div>`}
function news(){const relevant=(D.news||[]).filter(n=>(n.players_mentioned||[]).some(name=>(D.myTeam.players||[]).some(p=>p.name===name))).concat((D.news||[]).filter(n=>!(n.players_mentioned||[]).some(name=>(D.myTeam.players||[]).some(p=>p.name===name)))).slice(0,80);$('#view-news').innerHTML=`<div class="section-title"><div><div class="section-kicker">Fantasy-impact feed</div><h2>News Pulse</h2><p>Roster and market news is elevated first, with injury/role impact tagging.</p></div></div><div class="grid cols-2">${relevant.map(n=>`<div class="card news-card"><div class="news-meta"><span class="news-impact ${n.impact||'neutral'}">${(n.impact||'neutral').toUpperCase()}</span><span>${n.source||'News'}</span><span>${n.published||''}</span></div><a href="${n.link||'#'}" target="_blank" rel="noopener"><strong>${n.title}</strong></a><div class="sub">${n.summary||''}</div>${(n.players_mentioned||[]).length?`<div class="player-actions">${n.players_mentioned.slice(0,4).map(x=>`<span class="tag">${x}</span>`).join('')}</div>`:''}</div>`).join('')||'<div class="card empty">News feed is loading on the next hourly sync.</div>'}</div>`}
function league(){const rows=D.teams.map(t=>({t,g:teamGrade(t),QB:posGrade(t,'QB'),RB:posGrade(t,'RB'),WR:posGrade(t,'WR'),TE:posGrade(t,'TE')})).sort((a,b)=>b.g-a.g);$('#view-league').innerHTML=`<div class="section-title"><div><div class="section-kicker">Every opponent modeled</div><h2>League X-Ray</h2><p>Find who is strongest, who is thin, and where your trade leverage exists.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Rank</th><th>Manager</th><th>Power</th><th>QB</th><th>RB</th><th>WR</th><th>TE</th><th>Weakest</th></tr></thead><tbody>${rows.map((r,i)=>{const vals={QB:r.QB,RB:r.RB,WR:r.WR,TE:r.TE},w=Object.entries(vals).sort((a,b)=>a[1]-b[1])[0];return `<tr><td><span class="rank-badge">${i+1}</span></td><td><strong>${r.t.display_name}</strong>${r.t.roster_id===D.myTeam.roster_id?' <span class="tag good">YOU</span>':''}</td><td><strong>${r.g}</strong>${bar(r.g)}</td><td>${r.QB}</td><td>${r.RB}</td><td>${r.WR}</td><td>${r.TE}</td><td><span class="tag warn">${w[0]} ${w[1]}</span></td></tr>`}).join('')}</tbody></table></div><div class="section-title"><div><h2>Trade inventory scan</h2></div></div><div class="grid cols-3">${D.teams.filter(t=>t.roster_id!==D.myTeam.roster_id).map(t=>`<div class="card"><div class="label">${t.display_name}</div><div class="metric" style="font-size:18px">${teamGrade(t)} power</div>${t.players.filter(p=>!['K','DEF'].includes(p.position)).sort((a,b)=>value(b,b.starter)-value(a,a.starter)).slice(0,7).map(p=>`<span class="player-chip">${p.position} · ${p.name}</span>`).join('')}</div>`).join('')}</div>`}
function roster(){const pos=['QB','RB','WR','TE','K','DEF'];$('#view-roster').innerHTML=`<div class="grid cols-4">${['QB','RB','WR','TE'].map(x=>`<div class="card"><div class="label">${x} room</div><div class="metric">${posGrade(D.myTeam,x)}</div>${bar(posGrade(D.myTeam,x))}</div>`).join('')}</div>${pos.map(x=>`<div class="section-title"><div><h2>${x}</h2></div></div><div class="grid cols-3">${D.myTeam.players.filter(p=>p.position===x).sort((a,b)=>value(b,b.starter)-value(a,a.starter)).map(p=>`<div class="card">${player(p)}<div class="statline">${statline(p)}</div><div style="display:flex;justify-content:space-between;align-items:end;margin-top:12px"><div><div class="label">Hold value</div><div class="metric">${value(p,p.starter)}</div></div><span class="tag ${p.starter?'good':''}">${p.starter?'START':'BENCH'}</span></div>${bar(value(p,p.starter))}<p class="reason">${scheduleNote(p)}</p><button class="tiny-btn" onclick="openPlayer('${p.player_id}','mine')">Full case</button></div>`).join('')}</div>`).join('')}`}
function model(){$('#view-model').innerHTML=`<div class="hero"><div><div class="section-kicker">Transparent decision model</div><h2>Change what Jagger GM values.</h2><p>The default setup is optimized for this exact league format: shallow 10-team player pool, full PPR and two FLEX spots. In this format, elite weekly starters and high-volume RB/WR assets matter more than hoarding replacement-level depth.</p></div><div><div class="label">Data refresh</div><div class="metric" style="font-size:18px">Hourly</div><div class="sub">Sleeper + stats + schedule + news</div></div></div><div class="section-title"><div><h2>Waiver scoring weights</h2></div></div><div class="card model-box">${Object.entries(W).map(([k,v])=>`<div class="weight"><label>${k[0].toUpperCase()+k.slice(1)}</label><input data-w="${k}" type="range" min="0" max="50" value="${v}"><strong id="weight-${k}">${v}</strong></div>`).join('')}</div>`;$$('[data-w]').forEach(e=>e.oninput=()=>{W[e.dataset.w]=+e.value;$('#weight-'+e.dataset.w).textContent=e.value;command();waivers()})}
function installDrawer(){const d=document.createElement('aside');d.id='drawer';d.className='drawer';document.body.appendChild(d)}
window.openPlayer=function(id,where){const pools=where==='mine'?[D.myTeam]:D.teams;let p=null;if(where==='fa')p=D.freeAgents.find(x=>x.player_id===id);else for(const t of pools){p=(t.players||[]).find(x=>x.player_id===id);if(p)break}if(!p)return;const score=where==='fa'?waiverScore(p):value(p,p.starter),drops=dropList(),dr=drops[0];$('#drawer').innerHTML=`<button class="drawer-close" onclick="$('#drawer').classList.remove('open')">✕</button><div class="section-kicker">Player decision file</div><h2>${p.name}</h2>${player(p)}<div class="statline">${statline(p)}</div><div class="grid cols-2" style="margin-top:14px"><div class="mini"><b>${score}</b><span>${where==='fa'?'claim':'hold'} score</span></div><div class="mini"><b>${volumeScore(p)}</b><span>volume</span></div><div class="mini"><b>${health(p)}</b><span>health</span></div><div class="mini"><b>${upside(p)}</b><span>upside</span></div></div><div class="section-title"><div><h2>Recommendation logic</h2></div></div><div class="reason-list">${(where==='fa'?addReasons(p,dr):[dropReason(p),scheduleNote(p),`${ppg(p)||0} PPR/G in loaded 2026 stats`,`Sleeper market score ${Math.round(D.heat[p.player_id]||0)}`]).map(x=>`<div class="reason-item">${x}</div>`).join('')}</div><div class="section-title"><div><h2>Recent news</h2></div></div>${(p.news||[]).map(n=>`<div class="card news-card"><span class="news-impact ${n.impact}">${n.impact}</span><strong>${n.title}</strong><div class="sub">${n.summary||''}</div></div>`).join('')||'<div class="sub">No player-specific news in the current feed.</div>'}`;$('#drawer').classList.add('open')}
function bindNav(){$$('.nav-btn').forEach(b=>b.onclick=()=>{$$('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+b.dataset.view).classList.add('active');$('#pageTitle').textContent=b.querySelector('span').textContent;window.scrollTo({top:0,behavior:'smooth'})})}
boot();
