const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DATA={};
const WEIGHTS={need:28,heat:20,upside:18,scarcity:18,health:8,fit:8};
const POS_START={QB:1,RB:2,WR:2,TE:1,K:1,DEF:1};
const FLEX_POS=new Set(['RB','WR','TE']);

async function loadJSON(path){const r=await fetch(path+'?v='+Date.now());if(!r.ok)throw new Error(path);return r.json()}
async function boot(){
  try{
    const [status,league,teams,myTeam,freeAgents,trending,matchups,transactions,draftPicks]=await Promise.all([
      loadJSON('data/status.json'),loadJSON('data/league.json'),loadJSON('data/teams.json'),loadJSON('data/my_team.json'),loadJSON('data/free_agents.json'),loadJSON('data/trending.json'),loadJSON('data/matchups.json'),loadJSON('data/transactions.json'),loadJSON('data/draft_picks.json').catch(()=>[])
    ]);
    Object.assign(DATA,{status,league,teams,myTeam,freeAgents,trending,matchups,transactions,draftPicks});
    DATA.heat=buildHeat(trending); DATA.draftMap=buildDraftMap(draftPicks); DATA.owned=new Set(teams.flatMap(t=>t.players.map(p=>p.player_id)));
    $('#weekPill').textContent='Week '+status.current_week;
    $('#faabPill').textContent='FAAB $'+Math.max(0,(league.settings?.waiver_budget||0)-(myTeam.settings?.waiver_budget_used||0));
    $('#syncText').textContent='Synced '+timeAgo(status.refreshed_at_utc);
    renderAll(); bindNav();
  }catch(e){document.querySelector('main').innerHTML=`<div class="card"><h2>Data bridge unavailable</h2><p class="sub">${e.message}</p></div>`}
}
function timeAgo(iso){const m=Math.max(0,Math.floor((Date.now()-new Date(iso))/60000));return m<1?'just now':m<60?m+'m ago':Math.floor(m/60)+'h ago'}
function buildHeat(t){const m={};(t.add||[]).forEach((x,i)=>m[x.player_id]=(m[x.player_id]||0)+Math.max(0,100-i*1.4)+(x.count||0)*.08);(t.drop||[]).forEach((x,i)=>m[x.player_id]=(m[x.player_id]||0)-Math.max(0,60-i));return m}
function buildDraftMap(picks){const m={};for(const p of picks||[])m[p.player_id]=p;return m}
function draftCapital(p){const d=DATA.draftMap?.[p.player_id];if(!d)return 20;return Math.max(25,105-(d.pick_no||100)*1.15)}
function ageUpside(p){const y=Number(p.years_exp); if(!Number.isFinite(y))return 45; return y<=1?82:y<=3?72:y<=6?58:42}
function healthScore(p){if(!p.injury_status)return 100;return p.injury_status==='Questionable'?68:p.injury_status==='Doubtful'?35:p.injury_status==='Out'?18:45}
function posCounts(team){const c={QB:0,RB:0,WR:0,TE:0,K:0,DEF:0};team.players.forEach(p=>{if(c[p.position]!==undefined)c[p.position]++});return c}
function posNeed(team,pos){const c=posCounts(team);const min={QB:1,RB:4,WR:4,TE:2,K:1,DEF:1}[pos]||1;return Math.max(0,Math.min(100,(min-(c[pos]||0))*35+45))}
function scarcity(pos){return {RB:94,WR:88,TE:78,QB:52,K:22,DEF:28}[pos]||40}
function playerValue(p,starter=false){
  let v=draftCapital(p)*.46+ageUpside(p)*.16+healthScore(p)*.12+scarcity(p.position)*.15+(DATA.heat?.[p.player_id]||0)*.08+(starter?15:0);
  if(p.position==='K'||p.position==='DEF')v*=.58;
  return Math.max(1,Math.min(99,Math.round(v)));
}
function waiverScore(p){
  const need=posNeed(DATA.myTeam,p.position), heat=Math.max(0,Math.min(100,DATA.heat[p.player_id]||0)), up=ageUpside(p), sc=scarcity(p.position), health=healthScore(p), fit=(FLEX_POS.has(p.position)?88:55);
  return Math.round((need*WEIGHTS.need+heat*WEIGHTS.heat+up*WEIGHTS.upside+sc*WEIGHTS.scarcity+health*WEIGHTS.health+fit*WEIGHTS.fit)/100);
}
function faab(score,pos){const budget=DATA.league.settings?.waiver_budget||200;const pct=score>=88?.18:score>=80?.11:score>=72?.065:score>=64?.035:.012;let n=Math.round(budget*pct);if(pos==='QB'||pos==='TE')n=Math.round(n*.8);return Math.max(1,n)}
function pct(n){return `<div class="bar"><i style="width:${Math.max(3,Math.min(100,n))}%"></i></div>`}
function playerHTML(p){return `<div class="player"><span class="pos">${p.position||'?'}</span><div><strong>${p.name}</strong><div class="sub">${p.team||'FA'}${p.injury_status?' · '+p.injury_status:''}</div></div></div>`}
function rosterGrade(){const vals=DATA.myTeam.players.filter(p=>!['K','DEF'].includes(p.position)).map(p=>playerValue(p,p.starter)).sort((a,b)=>b-a);return Math.round(vals.slice(0,10).reduce((a,b)=>a+b,0)/Math.max(1,vals.slice(0,10).length))}
function positionGrade(pos){const arr=DATA.myTeam.players.filter(p=>p.position===pos).map(p=>playerValue(p,p.starter)).sort((a,b)=>b-a);const n={QB:1,RB:4,WR:4,TE:2}[pos]||1;return Math.round(arr.slice(0,n).reduce((a,b)=>a+b,0)/Math.max(1,arr.slice(0,n).length))}
function topWaivers(limit=10,pos='ALL'){return DATA.freeAgents.filter(p=>p.team&&p.status!=='Inactive'&&(pos==='ALL'||p.position===pos)).map(p=>({...p,wScore:waiverScore(p)})).sort((a,b)=>b.wScore-a.wScore).slice(0,limit)}
function dropCandidates(){return DATA.myTeam.players.filter(p=>!p.starter&&!['K','DEF'].includes(p.position)).map(p=>({...p,v:playerValue(p,false)})).sort((a,b)=>a.v-b.v)}
function renderAll(){renderCommand();renderWaivers();renderTrades();renderLeague();renderRoster();renderModel()}
function renderCommand(){
  const g=rosterGrade(), grades=['QB','RB','WR','TE'].map(positionGrade), weak=['QB','RB','WR','TE'][grades.indexOf(Math.min(...grades))];const waivers=topWaivers(5);const drops=dropCandidates();
  $('#view-command').innerHTML=`
  <div class="hero"><div><div class="label good">LIVE GM BRIEF</div><h2>Your biggest edge is making the next move before the room sees it.</h2><p>The model is built specifically around this league: 10 teams, full PPR, two FLEX spots, five bench slots, $${DATA.league.settings.waiver_budget} FAAB and your actual opponents. It rewards usable weekly ceiling, scarce RB/WR depth and trades that solve both managers' roster construction.</p></div><div class="callout"><div class="label">Current priority</div><div class="metric ${Math.min(...grades)<60?'warn':'good'}">${weak} depth</div><div class="sub">Lowest modeled position grade: ${Math.min(...grades)}/100</div></div></div>
  <div class="grid cols-4" style="margin-top:16px"><div class="card"><div class="label">Roster power</div><div class="metric">${g}</div>${pct(g)}<div class="sub">League-specific model</div></div><div class="card"><div class="label">Waiver priority</div><div class="metric good">#${DATA.myTeam.settings.waiver_position}</div><div class="sub">Use it only for a real difference-maker</div></div><div class="card"><div class="label">Best free agent</div><div class="metric" style="font-size:19px">${waivers[0]?.name||'—'}</div><div class="sub">Claim score ${waivers[0]?.wScore||'—'} · suggested $${waivers[0]?faab(waivers[0].wScore,waivers[0].position):0}</div></div><div class="card"><div class="label">Most expendable bench</div><div class="metric" style="font-size:19px">${drops[0]?.name||'—'}</div><div class="sub">Model value ${drops[0]?.v||'—'}</div></div></div>
  <div class="section-title"><div><h2>Moves worth checking first</h2><p>Not generic rankings — these are filtered through your roster construction.</p></div></div>
  <div class="grid cols-2">${waivers.slice(0,4).map((p,i)=>`<div class="card"><div class="label">${i===0?'Top waiver target':'Waiver watch #'+(i+1)}</div><div style="margin:10px 0">${playerHTML(p)}</div><div class="score">Claim score ${p.wScore}/100</div>${pct(p.wScore)}<p class="reason">${waiverReason(p)} Suggested FAAB: <strong>$${faab(p.wScore,p.position)}</strong>${drops[0]?` · Drop comparison: ${drops[0].name}`:''}</p></div>`).join('')}</div>`;
}
function waiverReason(p){const need=posNeed(DATA.myTeam,p.position),heat=DATA.heat[p.player_id]||0;let bits=[];if(need>55)bits.push(`your ${p.position} room needs depth`);if(heat>30)bits.push('strong market momentum');if(FLEX_POS.has(p.position))bits.push('two-FLEX lineup utility');if((p.years_exp??9)<=2)bits.push('young upside');return (bits.length?bits.join(', '):'depth and optionality')+'.'}
function renderWaivers(){
  $('#view-waivers').innerHTML=`<div class="section-title"><div><h2>Waiver Assassin</h2><p>Ranks only players who are actually unrostered in this league.</p></div><div class="controls"><input id="waiverSearch" class="control search" placeholder="Search player…"><select id="waiverPos" class="control"><option>ALL</option><option>RB</option><option>WR</option><option>TE</option><option>QB</option><option>K</option></select></div></div><div id="waiverTable"></div><div class="section-title"><div><h2>Drop ladder</h2><p>Bench players ordered from easiest to cut to hardest.</p></div></div><div class="grid cols-3">${dropCandidates().map((p,i)=>`<div class="card"><div class="label">Drop tier ${i+1}</div>${playerHTML(p)}<div class="metric">${p.v}</div><div class="sub">Hold value · ${p.injury_status||'healthy'}</div></div>`).join('')}</div>`;
  const update=()=>{const q=$('#waiverSearch').value.toLowerCase(),pos=$('#waiverPos').value;let list=DATA.freeAgents.filter(p=>p.team&&(pos==='ALL'||p.position===pos)&&p.name.toLowerCase().includes(q)).map(p=>({...p,wScore:waiverScore(p)})).sort((a,b)=>b.wScore-a.wScore).slice(0,80);$('#waiverTable').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Player</th><th>Claim Score</th><th>Market</th><th>Roster Need</th><th>FAAB</th><th>Action</th></tr></thead><tbody>${list.map((p,i)=>`<tr><td class="rank-num">${i+1}</td><td>${playerHTML(p)}</td><td><span class="score">${p.wScore}</span>${pct(p.wScore)}</td><td>${Math.round(DATA.heat[p.player_id]||0)}</td><td>${posNeed(DATA.myTeam,p.position)}</td><td><strong>$${faab(p.wScore,p.position)}</strong></td><td><span class="tag ${p.wScore>=78?'good':p.wScore>=65?'warn':''}">${p.wScore>=82?'CLAIM':p.wScore>=68?'WATCH':'DEPTH'}</span></td></tr>`).join('')}</tbody></table></div>`}; $('#waiverSearch').oninput=update;$('#waiverPos').onchange=update;update();
}
function teamStrength(t,pos){const a=t.players.filter(p=>p.position===pos).map(p=>playerValue(p,p.starter)).sort((a,b)=>b-a),n={QB:1,RB:3,WR:3,TE:1}[pos]||1;return Math.round(a.slice(0,n).reduce((x,y)=>x+y,0)/Math.max(1,a.slice(0,n).length))}
function tradeIdeas(){
 const my=DATA.myTeam, myGrades=Object.fromEntries(['QB','RB','WR','TE'].map(p=>[p,teamStrength(my,p)])); const mySurplus=[...my.players].filter(p=>!p.starter&&!['K','DEF'].includes(p.position)).sort((a,b)=>playerValue(b)-playerValue(a));let ideas=[];
 for(const opp of DATA.teams.filter(t=>t.roster_id!==my.roster_id)){
   for(const pos of ['RB','WR','TE','QB']){
     const theirPlayers=opp.players.filter(p=>p.position===pos).sort((a,b)=>playerValue(b,b.starter)-playerValue(a,a.starter)); if(!theirPlayers.length)continue;
     const target=theirPlayers[0], targetVal=playerValue(target,target.starter); const theirCounts=posCounts(opp); const surplus=theirCounts[pos]>(pos==='RB'||pos==='WR'?4:pos==='TE'?2:1);
     const needBoost=Math.max(0,78-myGrades[pos]);
     for(const give of mySurplus.slice(0,5)){
       const gv=playerValue(give,give.starter), oppNeed=Math.max(0,75-teamStrength(opp,give.position)); const fairness=100-Math.min(100,Math.abs(targetVal-gv)*2.4); const fit=Math.round(fairness*.48+oppNeed*.25+needBoost*.18+(surplus?15:0)); if(fit>48&&target.player_id!==give.player_id)ideas.push({opp,target,give,fit,targetVal,gv,pos});
     }
   }
 }
 return ideas.sort((a,b)=>b.fit-a.fit).slice(0,12)
}
function renderTrades(){const ideas=tradeIdeas();$('#view-trades').innerHTML=`<div class="hero"><div><div class="label purple">TRADE LAB</div><h2>Find the managers who have what you need — and need what you have.</h2><p>The fit score combines roster need, positional surplus, modeled player value and how likely the other roster is to improve from your offer. It is designed to find realistic conversations, not fantasy-trade-calculator nonsense.</p></div><div><div class="label">Top fit</div><div class="metric">${ideas[0]?.fit||'—'}</div><div class="sub">Negotiation fit / 100</div></div></div><div class="section-title"><div><h2>Best trade conversations</h2><p>Start here, then adjust the package rather than blindly sending offers.</p></div></div><div class="grid cols-2">${ideas.map((x,i)=>`<div class="card"><div style="display:flex;justify-content:space-between"><div class="label">#${i+1} · ${x.opp.display_name}</div><span class="tag ${x.fit>70?'good':'warn'}">FIT ${x.fit}</span></div><div class="trade-card" style="margin-top:12px"><div class="trade-side"><div class="sub">YOU SEND</div>${playerHTML(x.give)}<div class="sub">Value ${x.gv}</div></div><div class="trade-arrow">⇄</div><div class="trade-side"><div class="sub">YOU TARGET</div>${playerHTML(x.target)}<div class="sub">Value ${x.targetVal}</div></div></div><p class="reason">${x.opp.display_name} has ${posCounts(x.opp)[x.pos]} ${x.pos}s. This targets a position that grades below your strongest rooms while offering a bench asset at a position the other roster can use.</p></div>`).join('')||'<div class="empty">No clean one-for-one fits found. Use League X-Ray to build a 2-for-1.</div>'}</div>`}
function renderLeague(){const rows=DATA.teams.map(t=>({t,power:Math.round(['QB','RB','WR','TE'].map(p=>teamStrength(t,p)).reduce((a,b)=>a+b,0)/4),qb:teamStrength(t,'QB'),rb:teamStrength(t,'RB'),wr:teamStrength(t,'WR'),te:teamStrength(t,'TE')})).sort((a,b)=>b.power-a.power);$('#view-league').innerHTML=`<div class="section-title"><div><h2>League X-Ray</h2><p>See the roster construction behind every manager, including where trades are most likely.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Rank</th><th>Manager</th><th>Power</th><th>QB</th><th>RB</th><th>WR</th><th>TE</th><th>Likely Need</th></tr></thead><tbody>${rows.map((r,i)=>{const vals={QB:r.qb,RB:r.rb,WR:r.wr,TE:r.te},need=Object.entries(vals).sort((a,b)=>a[1]-b[1])[0][0];return `<tr><td class="rank-num">${i+1}</td><td><strong>${r.t.display_name}</strong>${r.t.roster_id===DATA.myTeam.roster_id?' <span class="tag good">YOU</span>':''}</td><td><span class="score">${r.power}</span>${pct(r.power)}</td><td>${r.qb}</td><td>${r.rb}</td><td>${r.wr}</td><td>${r.te}</td><td><span class="tag warn">${need}</span></td></tr>`}).join('')}</tbody></table></div><div class="section-title"><div><h2>Opponent inventories</h2><p>Clickless roster scan for trade planning.</p></div></div><div class="grid cols-3">${DATA.teams.filter(t=>t.roster_id!==DATA.myTeam.roster_id).map(t=>`<div class="card"><div class="label">${t.display_name}</div><div style="margin-top:9px">${t.players.filter(p=>!['K','DEF'].includes(p.position)).sort((a,b)=>playerValue(b,b.starter)-playerValue(a,a.starter)).slice(0,7).map(p=>`<span class="player-chip">${p.position} · ${p.name}</span>`).join('')}</div></div>`).join('')}</div>`}
function renderRoster(){const groups=['QB','RB','WR','TE','K','DEF'];$('#view-roster').innerHTML=`<div class="grid cols-4">${['QB','RB','WR','TE'].map(pos=>`<div class="card"><div class="label">${pos} grade</div><div class="metric">${positionGrade(pos)}</div>${pct(positionGrade(pos))}</div>`).join('')}</div>${groups.map(pos=>`<div class="section-title"><div><h2>${pos}</h2><p>${DATA.myTeam.players.filter(p=>p.position===pos).length} rostered</p></div></div><div class="grid cols-3">${DATA.myTeam.players.filter(p=>p.position===pos).sort((a,b)=>playerValue(b,b.starter)-playerValue(a,a.starter)).map(p=>`<div class="card">${playerHTML(p)}<div style="display:flex;justify-content:space-between;align-items:end;margin-top:12px"><div><div class="label">Model value</div><div class="metric">${playerValue(p,p.starter)}</div></div><span class="tag ${p.starter?'good':''}">${p.starter?'STARTER':'BENCH'}</span></div>${pct(playerValue(p,p.starter))}</div>`).join('')}</div>`).join('')}`}
function renderModel(){$('#view-model').innerHTML=`<div class="hero"><div><div class="label blue">DECISION MODEL</div><h2>You control what the algorithm cares about.</h2><p>Default weights are tuned for a shallow 10-team full-PPR league with two FLEX spots: replacement-level players are plentiful, so the model prioritizes ceiling, RB/WR scarcity and players who can actually crack your lineup.</p></div><div><div class="label">League facts</div><p class="reason">10 teams · 1 QB · 2 RB · 2 WR · 1 TE · 2 FLEX · 5 BN · $${DATA.league.settings.waiver_budget} FAAB · playoffs start Week ${DATA.league.settings.playoff_week_start}</p></div></div><div class="section-title"><div><h2>Waiver scoring weights</h2><p>Adjust these and every waiver score recalculates instantly.</p></div></div><div class="card model-box">${Object.entries(WEIGHTS).map(([k,v])=>`<div class="weight"><label>${k[0].toUpperCase()+k.slice(1)}</label><input type="range" min="0" max="50" value="${v}" data-weight="${k}"><strong id="w-${k}">${v}</strong></div>`).join('')}</div><div class="section-title"><div><h2>What the model knows</h2></div></div><div class="grid cols-3"><div class="card"><div class="label good">League aware</div><p class="reason">Actual owned/unowned players, opponent rosters, starters, bench, FAAB, waiver priority and lineup structure.</p></div><div class="card"><div class="label blue">Market aware</div><p class="reason">Sleeper 24-hour trending adds and drops are folded into waiver urgency.</p></div><div class="card"><div class="label purple">Fit aware</div><p class="reason">Trade ideas look for the intersection of your weakness, their surplus and their need for something you can give.</p></div></div>`;$$('[data-weight]').forEach(el=>el.oninput=()=>{WEIGHTS[el.dataset.weight]=+el.value;$('#w-'+el.dataset.weight).textContent=el.value;renderCommand();renderWaivers()})}
function bindNav(){$$('.nav-btn').forEach(b=>b.onclick=()=>{$$('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+b.dataset.view).classList.add('active');$('#pageTitle').textContent=b.querySelector('span').textContent})}
boot();
